package net.pdotudotsdot.cumulonimbus.entity.client;


import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class SkySpiderAnimations {

    public static final Animation SKY_SPIDER_IDLE = Animation.Builder.create(0f)
            .addBoneAnimation("leg0",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -22f, 3f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leg1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 22f, -3f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leg6",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -23f, 1f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("leg7",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 23f, 1f),
                                    Transformation.Interpolations.CUBIC))).build();
    public static final Animation SKY_SPIDER_WALK = Animation.Builder.create(0.75f).looping()
            .addBoneAnimation("leg0",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -22f, 3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06766667f, AnimationHelper.createRotationalVector(0f, -20f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, -17f, 8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.19167668f, AnimationHelper.createRotationalVector(0f, -13f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, -9f, 13f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.31676665f, AnimationHelper.createRotationalVector(0f, -4f, 15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, -2f, 17f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.44167665f, AnimationHelper.createRotationalVector(0f, -4f, 15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, -9f, 13f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5676667f, AnimationHelper.createRotationalVector(0f, -13f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, -17f, 8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6916767f, AnimationHelper.createRotationalVector(0f, -20f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, -22f, 3f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 22f, -3f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06766667f, AnimationHelper.createRotationalVector(0f, 20f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 17f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.19167668f, AnimationHelper.createRotationalVector(0f, 13f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 9f, -13f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.31676665f, AnimationHelper.createRotationalVector(0f, 4f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 2f, -17f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.44167665f, AnimationHelper.createRotationalVector(0f, 4f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 9f, -13f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5676667f, AnimationHelper.createRotationalVector(0f, 13f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 17f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6916767f, AnimationHelper.createRotationalVector(0f, 20f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 22f, -3f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg6",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -23f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06766667f, AnimationHelper.createRotationalVector(0f, -22f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, -20f, 4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.19167668f, AnimationHelper.createRotationalVector(0f, -17f, 7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, -12f, 9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.31676665f, AnimationHelper.createRotationalVector(0f, -8f, 12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, -2f, 14f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.44167665f, AnimationHelper.createRotationalVector(0f, -8f, 12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, -12f, 9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5676667f, AnimationHelper.createRotationalVector(0f, -17f, 7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, -20f, 4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6916767f, AnimationHelper.createRotationalVector(0f, -22f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, -23f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leg7",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 23f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06766667f, AnimationHelper.createRotationalVector(0f, 22f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 20f, -4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.19167668f, AnimationHelper.createRotationalVector(0f, 17f, -7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 12f, -9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.31676665f, AnimationHelper.createRotationalVector(0f, 8f, -12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 2f, -14f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.44167665f, AnimationHelper.createRotationalVector(0f, 8f, -12f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 12f, -9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5676667f, AnimationHelper.createRotationalVector(0f, 17f, -7f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 20f, -4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6916767f, AnimationHelper.createRotationalVector(0f, 22f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 23f, 1f),
                                    Transformation.Interpolations.LINEAR))).build();
}

